# Generated by Django 3.2.13 on 2022-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='books01.book'),
        ),
    ]
