# Generated by Django 3.2.13 on 2022-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0002_auto_20220514_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='introduce',
            field=models.CharField(default='nihao', max_length=128),
            preserve_default=False,
        ),
    ]
