# Generated by Django 3.2.13 on 2022-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0003_author_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.CharField(default='绪论', max_length=128),
            preserve_default=False,
        ),
    ]
