# Generated by Django 3.2.13 on 2022-05-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0004_book_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='dedail',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
