# Generated by Django 3.2.13 on 2022-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0006_auto_20220514_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='books01.book'),
        ),
    ]
