# Generated by Django 3.2.13 on 2022-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books01', '0007_auto_20220514_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='phone',
        ),
    ]
